import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./componets/Navbar/navbar"
import Providers from "./store/provider";
import { Toaster } from 'react-hot-toast';
import { PersistGate } from "redux-persist/integration/react";
import Footer from "./componets/Footer/Footer"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Gofarm",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         
          <Providers>
       <Navbar/>
         
  
      {children}
     
      <Toaster position="bottom-right" reverseOrder={false} />
      <Footer/>
      </Providers>  
      
   
      </body>

    </html>
  );
}
